// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.771
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func BaseLayout(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\" class=\"dark\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/ui/components/base_layout.templ`, Line: 9, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</title><script src=\"https://cdnjs.cloudflare.com/ajax/libs/htmx/1.9.6/htmx.min.js\"></script><script src=\"https://cdn.tailwindcss.com\"></script><script>\n                tailwind.config = {\n                    darkMode: \"class\",\n                    theme: {\n                        extend: {\n                            colors: {\n                                primary: {\n                                    50: \"#f0f9ff\",\n                                    100: \"#e0f2fe\",\n                                    200: \"#bae6fd\",\n                                    300: \"#7dd3fc\",\n                                    400: \"#38bdf8\",\n                                    500: \"#0ea5e9\",\n                                    600: \"#0284c7\",\n                                    700: \"#0369a1\",\n                                    800: \"#075985\",\n                                    900: \"#0c4a6e\",\n                                    950: \"#082f49\",\n                                },\n                            },\n                        },\n                    },\n                };\n            </script></head><body class=\"bg-gray-900 text-gray-100 min-h-screen flex flex-col\"><header class=\"bg-gray-800 py-4\"><div class=\"container mx-auto px-4\"><h1 class=\"text-2xl font-bold text-center text-primary-300\"><a href=\"/\">Nous </a></h1></div></header><main class=\"flex-grow container mx-auto px-4 py-8 flex flex-col relative\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</main><footer class=\"bg-gray-800 py-3\"><div class=\"container mx-auto px-4\"><p class=\"text-center text-gray-400 text-sm\">&copy; <span id=\"current-year\"></span> Nous. All rights reserved.</p></div></footer><script>\n                document.getElementById(\"current-year\").textContent = new Date().getFullYear();\n            </script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
